#ifndef DEF_OBJECTNAMEINFORMATION
#define DEF_OBJECTNAMEINFORMATION

typedef struct _OBJECT_NAME_INFORMATION {
  UNICODE_STRING Name;
} OBJECT_NAME_INFORMATION, *POBJECT_NAME_INFORMATION;

#endif // DEF_OBJECTNAMEINFORMATION
